### ISSUE TITLE
Release for 1.17 crashes in MC 1.17.1

### ISSUE THREAD

**Issue by phil535** [gnembon/carpet-autoCraftingTable#33]
The mod crashes the server as soon as you put an item in the crafting table.

```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 7/7/21, 8:09 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.class_2653.<init>(int, int, net.minecraft.class_1799)'
        at carpet_autocraftingtable.AutoCraftingTableContainer.method_7609(AutoCraftingTableContainer.java:46)
        at carpet_autocraftingtable.CraftingTableBlockEntity.method_5431(CraftingTableBlockEntity.java:160)
        at net.minecraft.class_1735.method_7668(class_1735.java:66)
        at net.minecraft.class_1735.method_7673(class_1735.java:62)
        at net.minecraft.class_1735.method_32755(class_1735.java:146)
        at net.minecraft.class_1703.method_30010(class_1703.java:405)
        at net.minecraft.class_1703.method_7593(class_1703.java:284)
        at net.minecraft.class_3244.method_12076(class_3244.java:1390)
        at net.minecraft.class_2813.method_12191(class_2813.java:55)
        at net.minecraft.class_2813.method_11054(class_2813.java:11)
        at net.minecraft.class_2600.method_11072(class_2600.java:21)
        at net.minecraft.class_3738.run(class_3738.java:18)
        at net.minecraft.class_1255.method_18859(class_1255.java:151)
        at net.minecraft.class_4093.method_18859(class_4093.java:23)
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788)
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
        at net.minecraft.class_1255.method_16075(class_1255.java:125)
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770)
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764)
        at net.minecraft.class_1255.method_5383(class_1255.java:110)
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748)
        at net.minecraft.server.MinecraftServer.handler$zgc000$modifiedRunLoop(MinecraftServer.java:2899)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
        at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.17.1
        Minecraft Version ID: 1.17.1
        Operating System: Linux (amd64) version 5.8.0-59-generic
        Java Version: 16.0.1, AdoptOpenJDK
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
        Memory: 3127515648 bytes (2982 MiB) / 6442450944 bytes (6144 MiB) up to 6442450944 bytes (6144 MiB)
        CPUs: 8
        Processor Vendor: GenuineIntel
        Processor Name: Intel Core Processor (Skylake, IBRS)
        Identifier: Intel64 Family 6 Model 94 Stepping 3
        Microarchitecture: Skylake (Client)
        Frequency (GHz): -0.00
        Number of physical packages: 8
        Number of physical CPUs: 8
        Number of logical CPUs: 8
        Graphics card #0 name: unknown
        Graphics card #0 vendor: unknown
        Graphics card #0 VRAM (MB): 0.00
        Graphics card #0 deviceId: unknown
        Graphics card #0 versionInfo: unknown
        Virtual memory max (MB): 9980.18
        Virtual memory used (MB): 5811.99
        Swap memory total (MB): 4022.00
        Swap memory used (MB): 0.00
        JVM Flags: 2 total; -Xms6G -Xmx6G
        Player Count: 1 / 20; [class_3222['Phil535'/110, l='ServerLevel[world]', x=234.04, y=64.00, z=727.22]]
        Data Packs: vanilla, file/afk display v1.1.0.zip, file/track raw statistics v1.4.0.zip
        Is Modded: Definitely; Server brand changed to 'fabric'
        Type: Dedicated Server (map_server.txt)
```

**Comment by gnembon** [comment]
not anymore with 1.4.43
