### ISSUE TITLE
Update to 1.18.2

### ISSUE THREAD

**Issue by Yadokingu** [gnembon/carpet-autoCraftingTable#54]
Could you update this extension to 1.18.2? Would be much appreciated.

**Comment by orlp** [comment]
Getting this error when trying to run it with 1.18.2:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'carpet'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ExceptionInInitializerError
	at carpet_autocraftingtable.AutoCraftingTable.onGameStarted(AutoCraftingTable.java:17)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at carpet.CarpetServer.onGameStarted(CarpetServer.java:78)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 19 more
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:block_entity_type / carpet:crafting_table])
	at net.minecraft.class_2370.method_40274(class_2370.java:80)
	at net.minecraft.class_2370.method_31051(class_2370.java:90)
	at net.minecraft.class_2370.method_10273(class_2370.java:86)
	at net.minecraft.class_2370.method_10272(class_2370.java:134)
	at net.minecraft.class_2378.method_39197(class_2378.java:471)
	at net.minecraft.class_2378.method_10230(class_2378.java:467)
	at net.minecraft.class_2378.method_10226(class_2378.java:463)
	at carpet_autocraftingtable.CraftingTableBlockEntity.<clinit>(CraftingTableBlockEntity.java:35)
	... 23 more
```

**Comment by gazi14-kagwa** [comment]
How do I download it?
